services:
  amc-chat-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: amchem-chat-ui
    container_name: amchem-chat
    volumes:
      - amc-chat-vol:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - amc-chat-service

volumes:
  amc-chat-vol: {}
